### ISSUE TITLE
FurnaceRecipe Creation Lacks Sanity Checks

### ISSUE THREAD

**Issue by Jikoo** [ryandw11/CoralStay#1]
Per Jikoo/EnchantableBlocks#3, CoralStay does not perform any sanity checks when creating recipes.

From [this debug line](https://github.com/Jikoo/EnchantableBlocks/blob/dfa8669a34be38d6732e5943939a5c8f2d20daad/src/main/java/com/github/jikoo/enchantableblocks/util/CompatibilityUtil.java#L267):
`Recipe with null InputChoice: minecraft:coralstay_fire_coral_wall_fan outputting ItemStack{AIR x 0}`

Inputs and results should be checked to ensure they're valid non-air materials prior to creation.
You also should be using your plugin name for recipe namespacing, but that's less important.

**Comment by ryandw11** [comment]
Nice catch, that bug has been there for awhile.

**Comment by ryandw11** [comment]
While testing it using your plugin it gives this error https://pastebin.com/MXUdXiLr
The bug is given both with the coral blocks and with normal iron ore. Is this a bug on your end or is it still by end?

**Comment by ryandw11** [comment]
A little confused with this. 
```java
FurnaceRecipe fr = new FurnaceRecipe(new NamespacedKey(this, m.toString().toLowerCase()), result, m, 1, getConfig().getInt("Cook_Time"));
```
What would I need to check to be valid before creating it? I know that everything I put into the recipe is valid.

**Comment by Jikoo** [comment]
According to my debug, you're creating a recipe with an input and output of air. As long as the input isn't air, it'll at least be useable by other plugins, but honestly, after a look over your code, I'm not sure how either would be possible. Maybe the user who reported it has additional blocks configured which don't have dead variants? Either way, should include a check for it just in case.
@aurel85 if you would, your CoralStay config might be helpful.

I've also opened [SPIGOT-4587](https://hub.spigotmc.org/jira/browse/SPIGOT-4587) because CB shouldn't be allowing invalid recipes to be registered.

Edit: ~~Actually, based on the key derived from the material name I would assume it should be fine. Pretty confused. Really wish I had the ability to load MC so I could test this stuff myself.~~
Wall variants are not valid for ItemStacks, they're variants of regular fans that are block-only.

**Comment by aurel85** [comment]
Hi,

My CoralStay config : https://www.dropbox.com/s/q4pw4qbj21odvnq/config.yml?dl=0

Note that with the latest version of EnchantableBlocks (https://github.com/Jikoo/EnchantableBlocks/issues/3#issuecomment-455888481) everything is ok, with enchanted furnace and the corals in the furnace !

**Comment by ryandw11** [comment]
I used EnchantableBlocks and CoralStay on a clean server using default configs and still got the error. I added a check to the plugin so that if the recipe had an input or output value of air it wouldn't register it.

**Comment by Jikoo** [comment]
Yeah, sorry, I edited my comment once I figured it out.
>Wall variants are not valid for ItemStacks, they're variants of regular fans that are block-only.

Check Material#isItem, the wall variants are block-only.

**Comment by ryandw11** [comment]
Thank you for the assistance. I fixed the bug.
